spring.application.name=credential-verification
server.port=8060

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=URP

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# ----------------------------
# IPFS CONFIG (NEW)
# ----------------------------

# Local IPFS node API (Kubo default)
ipfs.api.url=http://127.0.0.1:5001

# Optional: gateway for file preview
ipfs.gateway.url=https://ipfs.io/ipfs/

# ----------------------------
# HYPERLEDGER FABRIC CONFIG
# ----------------------------

fabric.network.channelName=mychannel
fabric.network.chaincodeName=certificatecc
fabric.network.mspId=Org1MSP

jwt.secret=your-very-long-secret-key-at-least-32-chars
jwt.expiration=86400000

fabric.network.peer.endpoint=188.166.207.81:7051
fabric.network.peer.tlsCert=src/main/resources/fabric/org1-peer-tlsca.pem
fabric.network.peer.overrideAuth=peer0.org1.example.com

fabric.network.orderer.endpoint=188.166.207.81:7050
fabric.network.orderer.tlsCert=src/main/resources/fabric/orderer-tlsca.pem

fabric.network.identity.cert=src/main/resources/fabric/user1-cert.pem
fabric.network.identity.key=${FABRIC_IDENTITY_KEY:src/main/resources/fabric/user1-key.pem}

aes.secret=mySuperSecretKey123